spring.application.name=The_Clinic_Car_Wash_Backend

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/The_Clinic_Car_Wash
spring.data.mongodb.database=carwash

logging.level.com.shineco=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000