spring.application.name=The_Clinic_Car_Wash_Backend

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/The_Clinic_Car_Wash
spring.data.mongodb.database=The_Clinic_Car_Wash

logging.level.com.shineco=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

twilio.account-sid=ACf1d2bf18a792c9f302816e30a8cc47a3
twilio.auth-token=f08b0d7ad53ebf4547d14eb170294afa
twilio.whatsapp-from=whatsapp:+14155238886

spring.main.allow-bean-definition-overriding=true

payfast.merchant-id=10048009
payfast.merchant-key=rgwovyme9n74l
payfast.passphrase=ClingCarWash
payfast.sandbox=true
 
# Replace YOUR_NGROK_URL after running: ngrok http 8080
payfast.notify-url=https://iona-submucous-zona.ngrok-free.dev/api/payments/payfast/notify
payfast.return-url=http://localhost:5173/payment-success
payfast.cancel-url=http://localhost:5173/payment-cancelled